<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2017-12-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Blog Extension',
    'description' => 'This is the didactical example from the book \"TYPO3 Extbase\" by Patrick Lobacher',
    'category' => 'plugin',
    'author' => 'Patrick Lobacher',
    'author_email' => 'patrick@lobacher.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => array(
        'psr-4' => array('Pluswerk\\Simpleblog\\' => 'Classes')
    ),
];
